image_size: 256
batch_size: 8
lr: 0.0002
num_epochs: 10

content_dir: data/faces
style_dir: data/styles
style_classes_path: training/style_classes.json

checkpoint_path: training/checkpoints/stylizer_net.pth
num_workers: 2
